---
title: "Classification accuracy goals for diagnostic tests based on risk stratification"
author:
- Ty Nguyen and Gene Pennello
- FDA Division of Imaging, Diagnostics, & Software Reliability
---
<style type="text/css">
body{
  font-size: 12pt;
#  color: DarkRed;
}
</style>
<br>

#### 1. Notation

##### 1.1 $D=0,1$ indicate absence, presence of target condition

##### 1.2 $T=0,1$ indicates index test T is negative, positive for target condition

##### 1.3 $p=Pr⁡(D=1$) is prevalence (pre-test probability) of the target condition.

##### 1.4 $τ=Pr⁡(T=1$) is probability test is positive for target condition
##### 1.5 Predictive values
$p_t=Pr⁡(D=1|T=1)$= predictive value of T=t for target conditiot

$p_0=Pr⁡(D=1│T=0)=1-NPV$

$p_1=Pr⁡(D=1│T=1)=PPV$

##### 1.6 Risk Stratification Differences
$d_0=p-p_0$ = pre- to post-test difference if test is negative for target condition

$d_1=p_1-p$=post- to pre-test difference if test is positive for target condition

##### 1.7 Test positive fractions
$\tau_d=Pr⁡(T=1│D=d)$= test positive fraction for D=d

$τ_0=Pr⁡(T=1│D=0)=FPF=1-Sp$

$\tau_1=Pr⁡(T=1│D=1)=TPF=Se$
	
#### 1.8 Diagnostic Likelihood Ratios

$l_0=\frac{Pr⁡(T=1│D=0)}{Pr⁡(T=0│D=0)} =\frac{(1-τ_1)}{(1-τ_0 )}=\frac{(1-Se)}{Sp}$=negative likelihood ratio

$l_1=\frac{Pr⁡(T=1│D=1)}{Pr⁡(T=0│D=1)} =\frac{(τ_1)}{( τ_0 )}=\frac{Se}{1-Sp}$=positive likelihood ratio

#### 2. Basic Relations
##### 2.1 Bayes Theorem

$o_t=l_t\ o$, where $o_t=\frac{p_t}{(1-p_t\ )}$=post- test odds,$\ o=\frac{p}{(1-p)}$= pre-test odds

##### 2.2 Relations Between Test Positive Fractions and Likelihood Ratios

$\tau_0=(1-l_0)/(l_1-l_0\ ),1-\tau_0=(l_1-1)/(l_1-l_0\ )=Sp$ 

$\tau_1=l_1\ \tau_0=l_1\ \ (1-l_0)/(l_1-l_0\ )=Se$

##### 2.3 Relations for Risk Stratification Differences

$d_0=p-p_0=\tau(p_1-p_0\ )$, i.e., $\tau=(p-p_0)/(p_1-p_0\ )$

$d_1=p_1-p=(1-\tau)(p_1-p_0\ )$

##### 2.4 Additional Relations

$\tau-\tau_0=p(\tau_1-\tau_0\ )$, i.e., $p=(\tau-\tau_0)/(\tau_1-\tau_0\ )$

$\tau_1-\tau=(1-p)(\tau_1-\tau_0\ )$

##### 2.5 Mean Risk Stratification (MRS) (Katki):

$MRS=(1-\tau)(p-p_0\ )+\tau(p_1-p)=\ 2\tau(p_1-p)$

$=(1-p)(\tau-\tau_0\ )+p(\tau_1-\tau)=\ 2p(\tau_1-\tau)$

$=(1-\tau)\tau(\tau_1-\tau_0\ )\equiv(1-p)p(YI)$

$=(1-\tau)\tau(p_1-p_0\ )=(1-\tau)\tau(PPV+NPV-1)$

$=2(cross\ product\ of\ 2\ \times2\ probability\ table)$

where $YI\ =\tau_1-\tau_0=TPF+FPF-1= Youden’s Index$.

##### 3. Standalone Studies of One Diagnostic Test. 

##### 3.1 The software translates user input of risk stratification goals

##### 3.1.1 $(p,p_1^\ast\ )$ to a PG $ l_1^\ast\$\ for PLR, 

##### 3.1.2 $(p_0^\ast,p)$ to a PG $l_0^\ast$\ \ for NLR, 

##### 3.1.3 $(p_0^\ast,p,p_1^\ast\ )$ to PGs  $1-\tau_0^\ast$ and $\tau_1^\ast$ for $Sp$ and $Se$ based on the corresponding $PLR$ and $NLR$ PGs (see Section 3.2).
The PGs are determined based on Bayes Theorem (2.1) and the relations given in (2.2).

#####  3.2 The software plots the standalone PGs $l_0^\ast,l_1^\ast, \tau_0^\ast$, and $\tau_1^\ast$ for $NLR, PLR, 1-Sp$, and $Se$ on the likelihood ratio graph (Biggerstaff, 2000) of the PLR and NLR lines corresponding to the PGs.

The PLR line is $y=l_1^\ast\ x$. The NLR line is $y=1-l_0^\ast+l_0^\ast\ x$.

The two lines intersect at $(x,y)=(1-l_0^\ast)/(l_1^\ast-l_0^\ast\ )\ (1,l_1^\ast\ )=(\tau_0^\ast,\tau_1^\ast\ )$,
which are the PGs for $1–Sp$ and $Se$.  As is clear from the likelihood ratio graph, the $Sp$ and $Se$ values meeting PGs $1-\tau_0^\ast$ and $\tau_1^\ast$ are only a subset of those meeting the NLR and PLR PGs  $l_0^\ast$ and $l_1^\ast$ and thus less flexible for the same desired risk stratification.  Studies designed to meet $NLR$ and $PLR$ PGs are therefore less burdensome than those designed to meet $Sp$ and $Se$ PGs. The reason $Sp$ and $Se$ PGs are less flexible is that by Bayes Theorem (2.1), diagnostic likelihood ratios are the quantities by which pre-test odds are modified to post-test odds and therefore are more naturally related to risk stratification than $1-Sp$ and $Se$. 
The software performs data analysis of standalone data, comparing the estimates and 95% confidence intervals for $Se, Sp, PLR$, and $NLR$ and against their PGs.







