---
title: "Classification accuracy goals for diagnostic tests based on risk stratification"
author:
- Ty Nguyen and Gene Pennello
- FDA Division of Imaging, Diagnostics, & Software Reliability
---
<style type="text/css">
body{
  font-size: 12pt;
#  color: DarkRed;
}
</style>
<br>

Diagnostic tests classify the binary status of a target condition (e.g., absent, present). Classification accuracy measures include sensitivity (Se), specificity (Sp), positive likelihood ratio PLR = Se / (1 – Sp), negative likelihood ratio NLR = (1 – Se)/Sp, and receiver operating characteristic curve (ROC). Classification accuracy measures are popular because they do not depend on the prevalence (i.e., pre-test probability) of the target condition and thus for low prevalence conditions can be estimated without bias in a moderately-sized, well-conducted study enriched with subjects having the condition. 

Unfortunately, performance goals (PGs) for classification accuracy are often chosen with only a vague understanding of whether they confer that the test would be clinically useful in practice. Clinicians often think the PGs should be set by the statisticians. Statisticians think the PGs should be set by the clinicians!

A framework is needed for how to set clinically meaningful PGs for classification accuracy. Such a framework would improve conversations among stakeholders (Patients / FDA / Industry / Payers) on appropriate acceptance criteria for validating a diagnostic test for its intended use. 

Clinically meaningful PGs for classification accuracy may be determined based on desired risk stratification. A diagnostic test has good risk stratification if it stratifies large proportions of the test population into meaningful categories of high and/or low risk for the target condition of the test (Wentzensen and Wacholder, 2012; Castle and Katki, 2016). The high and low risk categories are meaningful if they are recommended for guiding clinical management options. Risk stratification is defined by the triple $(p_0,p,p_1 )$, where 

. $p$ is the prevalence (i.e., pre-test probability) of the target condition of the test, 
	
. $p_1>p$ is the positive predictive value (PPV) of the test, which defines the high risk category, and 
	
. $p_0<p$ is one minus the negative predictive value (NPV) of the test, which defines the low risk category.

Risk thresholds $p_0$ and $p_1$ may be taken from an accepted clinical guideline that recommends a particular clinical management option if a subject’s risk for the target condition exceeds $p_1$ or another option if it is less than $p_0$. 


Contacts

•	NgocTy.Nguyen@fda.hhs.gov

•	Gene.Pennello@fda.hhs.gov







